# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container1', '.']
  
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/container1']
  
#   - name: 'gcr.io/cloud-builders/kubectl'
#     args: ['apply', '-f', 'container1-deployment.yaml']
#     env:
#       - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#       - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
#
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/your-project-id/my-repo/container1:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/your-project-id/my-repo/container1:latest']
images:
  - 'us-central1-docker.pkg.dev/your-project-id/my-repo/container1:latest'

options:
  logging: 'NONE'  # No logs generated

